WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
INFO:app:Health check successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:15:37] "GET /healthz HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:15:58] "GET /metrics HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:18:16] "GET /metrics HTTP/1.1" 200 -
INFO:app:Health check successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:18:20] "GET /healthz HTTP/1.1" 200 -
INFO:app:Main request successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:18:24] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:18:24] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:18:30] "[33mGET /noend HTTP/1.1[0m" 404 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 56, in metrics
    response=json.dumps({"status":"success","data":{"db_connection_count": "count_conn","post_count": count_posts()}}),
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Row is not JSON serializable
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:25:11] "[35m[1mGET /metrics HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:28:17] "GET /metrics HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:29:32] "GET /metrics HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:30:18] "GET /metrics HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 58, in metrics
    response=json.dumps({"status":"success","data":{"db_connection_count": "count_conn","post_count": count_posts()}}),
  File "app.py", line 25, in count_posts
    connection = get_db_connection()
  File "app.py", line 10, in get_db_connection
    counter+=1
UnboundLocalError: local variable 'counter' referenced before assignment
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:52:48] "[35m[1mGET /metrics HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 70, in index
    connection = get_db_connection()
  File "app.py", line 10, in get_db_connection
    counter+=1
UnboundLocalError: local variable 'counter' referenced before assignment
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:53:18] "[35m[1mGET / HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 72, in index
    connection = get_db_connection()
  File "app.py", line 12, in get_db_connection
    Counter+=1
UnboundLocalError: local variable 'Counter' referenced before assignment
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:54:32] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 72, in index
    connection = get_db_connection()
  File "app.py", line 12, in get_db_connection
    Counter+=1
UnboundLocalError: local variable 'Counter' referenced before assignment
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:54:33] "[35m[1mGET / HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 72, in index
    connection = get_db_connection()
  File "app.py", line 14, in get_db_connection
    connection.Counter+=1
AttributeError: 'sqlite3.Connection' object has no attribute 'Counter'
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:57:48] "[35m[1mGET / HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 72, in index
    connection = get_db_connection()
  File "app.py", line 12, in get_db_connection
    Counter+=1
UnboundLocalError: local variable 'Counter' referenced before assignment
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 17:59:14] "[35m[1mGET / HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
INFO:app:Main request successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:00:07] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:00:07] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:app:Health check successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:00:13] "GET /healthz HTTP/1.1" 200 -
INFO:app:Metrics request successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:00:17] "GET /metrics HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 60, in metrics
    response=json.dumps({"status":"success","data":{"db_connection_count": "count_conn","post_count": count_posts()}}),
  File "app.py", line 27, in count_posts
    connection = get_db_connection()
  File "app.py", line 12, in get_db_connection
    Counter+=1
UnboundLocalError: local variable 'Counter' referenced before assignment
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:02:08] "[35m[1mGET /metrics HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /metrics [GET]
Traceback (most recent call last):
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wyndell.lowie/nd064_course_1/project/techtrends/.myvenv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 60, in metrics
    response=json.dumps({"status":"success","data":{"db_connection_count": "count_conn","post_count": count_posts()}}),
  File "app.py", line 27, in count_posts
    connection = get_db_connection()
  File "app.py", line 12, in get_db_connection
    Counter=Counter+1
UnboundLocalError: local variable 'Counter' referenced before assignment
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:04:20] "[35m[1mGET /metrics HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
INFO:app:Metrics request successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:05:35] "GET /metrics HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
INFO:app:Main request successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:06:28] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:06:28] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:app:Health check successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:06:32] "GET /healthz HTTP/1.1" 200 -
INFO:app:Metrics request successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:06:35] "GET /metrics HTTP/1.1" 200 -
INFO:app:Main request successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:06:46] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:06:46] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:app:Health check successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:06:52] "GET /healthz HTTP/1.1" 200 -
INFO:app:Metrics request successful
INFO:werkzeug:192.168.0.18 - - [25/Oct/2022 18:06:58] "GET /metrics HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
INFO:app:Main request successful
INFO:werkzeug:127.0.0.1 - - [28/Oct/2022 14:59:13] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Oct/2022 14:59:13] "GET /static/css/main.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Oct/2022 14:59:13] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [28/Oct/2022 14:59:18] "GET /about HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Oct/2022 14:59:18] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:app:Metrics request successful
INFO:werkzeug:127.0.0.1 - - [28/Oct/2022 14:59:26] "GET /metrics HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Oct/2022 14:59:46] "[33mGET /noend HTTP/1.1[0m" 404 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
INFO:app:Main request successful
INFO:werkzeug:127.0.0.1 - - [31/Oct/2022 11:46:23] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Oct/2022 11:46:23] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:app:Health check successful
INFO:werkzeug:127.0.0.1 - - [31/Oct/2022 11:46:28] "GET /healthz HTTP/1.1" 200 -
INFO:app:Metrics request successful
INFO:werkzeug:127.0.0.1 - - [31/Oct/2022 11:46:35] "GET /metrics HTTP/1.1" 200 -
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.0.18:3111/ (Press CTRL+C to quit)
